### PR TITLE
[ci] Enable .nupkg signing

### PR DESCRIPTION
**Pull request by pjcollins**
We'll want to release a new version of this package to nuget.org in the
near future, as the latest stable version does not work with the .NET 6
Android SDK.  We'll want to enable package signing to release an updated
version.

### CODE REVIEW

**Comment by mattleibow** [comment]
I have found the real issue here, but I can't seem to fix it. The issue is, you are using `PublishPipelineArtifact`, and the signing job is using `DownloadBuildArtifacts`. These appear to not be compatible: 
```
Unsupported artifact type: PipelineArtifact
Successfully downloaded artifacts to C:\A\1\_temp\artifact-signing\unsigned
```

And then the step succeeds but actually failed...

I tried switching the signing task to also support `DownloadPipelineArtifact` so it doesn't matter, but for some reason it just can't work. It jut ignores my parameters. They are right, because invalid parameters will fail.

So, to get this building, I just switched to `PublishBuildArtifacts`. 

Unless you _need_ `PublishPipelineArtifact`, this should be fine.

**Comment by pjcollins** [comment]
Thanks for the investigation @mattleibow!

I'll wait to merge this until real signing is approved for this build definition.

**Pull request merged**
